// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCV71aKAbjLw7g1fcLFQ3I8lbN-7nRwsU',
    appId: '1:1037602740027:web:cbb1ca32b9747d44b3091e',
    messagingSenderId: '1037602740027',
    projectId: 'beathub-35769',
    authDomain: 'beathub-35769.firebaseapp.com',
    storageBucket: 'beathub-35769.firebasestorage.app',
    measurementId: 'G-CK6FVQ7CWM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4ZIwPgdaQsEMwpZuqzpfrLuf5NHB93qE',
    appId: '1:1037602740027:android:8e4b833c02479947b3091e',
    messagingSenderId: '1037602740027',
    projectId: 'beathub-35769',
    storageBucket: 'beathub-35769.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz1CWXyeO5LKtAf3sbJ03HF8jMSQVFm7Q',
    appId: '1:1037602740027:ios:b2c38bd57a9f44c9b3091e',
    messagingSenderId: '1037602740027',
    projectId: 'beathub-35769',
    storageBucket: 'beathub-35769.firebasestorage.app',
    iosBundleId: 'com.example.beathubFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz1CWXyeO5LKtAf3sbJ03HF8jMSQVFm7Q',
    appId: '1:1037602740027:ios:b2c38bd57a9f44c9b3091e',
    messagingSenderId: '1037602740027',
    projectId: 'beathub-35769',
    storageBucket: 'beathub-35769.firebasestorage.app',
    iosBundleId: 'com.example.beathubFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCV71aKAbjLw7g1fcLFQ3I8lbN-7nRwsU',
    appId: '1:1037602740027:web:c70cd753966b0cf2b3091e',
    messagingSenderId: '1037602740027',
    projectId: 'beathub-35769',
    authDomain: 'beathub-35769.firebaseapp.com',
    storageBucket: 'beathub-35769.firebasestorage.app',
    measurementId: 'G-9M82ZEVHDQ',
  );
}
